"use client";

import { useState } from "react";
import { ToolLayout } from "@/components/tool-layout";
import { CopyButton } from "@/components/copy-button";
import { Plus, Trash2 } from "lucide-react";

interface Redirect {
  id: string;
  type: "301" | "302";
  from: string;
  to: string;
}

interface RewriteRule {
  id: string;
  pattern: string;
  substitution: string;
  flags: string;
}

interface ErrorPage {
  code: string;
  path: string;
}

interface BlockedIP {
  id: string;
  ip: string;
}

interface HotlinkDomain {
  id: string;
  domain: string;
}

const defaultErrorPages: ErrorPage[] = [
  { code: "404", path: "" },
  { code: "403", path: "" },
  { code: "500", path: "" },
];

export function HtaccessGeneratorTool() {
  // Redirects
  const [redirects, setRedirects] = useState<Redirect[]>([]);
  // Rewrite rules
  const [rewriteRules, setRewriteRules] = useState<RewriteRule[]>([]);
  // Error pages
  const [errorPages, setErrorPages] = useState<ErrorPage[]>(defaultErrorPages);
  // Directory listing
  const [directoryListing, setDirectoryListing] = useState<"default" | "enable" | "disable">("default");
  // Hotlink protection
  const [hotlinkEnabled, setHotlinkEnabled] = useState(false);
  const [hotlinkDomains, setHotlinkDomains] = useState<HotlinkDomain[]>([]);
  // CORS
  const [corsEnabled, setCorsEnabled] = useState(false);
  const [corsOrigin, setCorsOrigin] = useState("*");
  // Gzip
  const [gzipEnabled, setGzipEnabled] = useState(false);
  // Browser caching
  const [cachingEnabled, setCachingEnabled] = useState(false);
  const [cacheMaxAge, setCacheMaxAge] = useState("2592000");
  // Force HTTPS
  const [forceHttps, setForceHttps] = useState(false);
  // Force www
  const [wwwMode, setWwwMode] = useState<"default" | "www" | "non-www">("default");
  // Block IPs
  const [blockedIPs, setBlockedIPs] = useState<BlockedIP[]>([]);
  // Password protection
  const [passwordEnabled, setPasswordEnabled] = useState(false);
  const [authName, setAuthName] = useState("Protected Area");
  const [htpasswdPath, setHtpasswdPath] = useState("/etc/apache2/.htpasswd");

  const addRedirect = () =>
    setRedirects((r) => [...r, { id: crypto.randomUUID(), type: "301", from: "", to: "" }]);
  const removeRedirect = (id: string) => setRedirects((r) => r.filter((x) => x.id !== id));
  const updateRedirect = (id: string, field: keyof Redirect, value: string) =>
    setRedirects((r) => r.map((x) => (x.id === id ? { ...x, [field]: value } : x)));

  const addRewriteRule = () =>
    setRewriteRules((r) => [...r, { id: crypto.randomUUID(), pattern: "", substitution: "", flags: "L" }]);
  const removeRewriteRule = (id: string) => setRewriteRules((r) => r.filter((x) => x.id !== id));
  const updateRewriteRule = (id: string, field: keyof RewriteRule, value: string) =>
    setRewriteRules((r) => r.map((x) => (x.id === id ? { ...x, [field]: value } : x)));

  const updateErrorPage = (code: string, path: string) =>
    setErrorPages((e) => e.map((x) => (x.code === code ? { ...x, path } : x)));

  const addBlockedIP = () => setBlockedIPs((b) => [...b, { id: crypto.randomUUID(), ip: "" }]);
  const removeBlockedIP = (id: string) => setBlockedIPs((b) => b.filter((x) => x.id !== id));
  const updateBlockedIP = (id: string, ip: string) =>
    setBlockedIPs((b) => b.map((x) => (x.id === id ? { ...x, ip } : x)));

  const addHotlinkDomain = () => setHotlinkDomains((d) => [...d, { id: crypto.randomUUID(), domain: "" }]);
  const removeHotlinkDomain = (id: string) => setHotlinkDomains((d) => d.filter((x) => x.id !== id));
  const updateHotlinkDomain = (id: string, domain: string) =>
    setHotlinkDomains((d) => d.map((x) => (x.id === id ? { ...x, domain } : x)));

  const generateHtaccess = (): string => {
    const lines: string[] = ["# Generated by devpick.sh/.htaccess Generator", ""];

    // Force HTTPS
    if (forceHttps) {
      lines.push("# Force HTTPS");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTPS} off");
      lines.push("RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
      lines.push("");
    }

    // Force www / non-www
    if (wwwMode === "www") {
      lines.push("# Force www");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTP_HOST} !^www\\.");
      lines.push("RewriteRule ^ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
      lines.push("");
    } else if (wwwMode === "non-www") {
      lines.push("# Force non-www");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]");
      lines.push("RewriteRule ^ https://%1%{REQUEST_URI} [L,R=301]");
      lines.push("");
    }

    // Redirects
    const validRedirects = redirects.filter((r) => r.from && r.to);
    if (validRedirects.length > 0) {
      lines.push("# Redirects");
      for (const r of validRedirects) {
        lines.push(`Redirect ${r.type} ${r.from} ${r.to}`);
      }
      lines.push("");
    }

    // URL Rewriting
    const validRules = rewriteRules.filter((r) => r.pattern && r.substitution);
    if (validRules.length > 0) {
      lines.push("# URL Rewriting");
      lines.push("RewriteEngine On");
      for (const r of validRules) {
        lines.push(`RewriteRule ${r.pattern} ${r.substitution} [${r.flags}]`);
      }
      lines.push("");
    }

    // Error pages
    const validErrors = errorPages.filter((e) => e.path);
    if (validErrors.length > 0) {
      lines.push("# Custom Error Pages");
      for (const e of validErrors) {
        lines.push(`ErrorDocument ${e.code} ${e.path}`);
      }
      lines.push("");
    }

    // Directory listing
    if (directoryListing === "enable") {
      lines.push("# Directory Listing");
      lines.push("Options +Indexes");
      lines.push("");
    } else if (directoryListing === "disable") {
      lines.push("# Disable Directory Listing");
      lines.push("Options -Indexes");
      lines.push("");
    }

    // Hotlink protection
    if (hotlinkEnabled) {
      const domains = hotlinkDomains.filter((d) => d.domain).map((d) => d.domain);
      if (domains.length > 0) {
        lines.push("# Hotlink Protection");
        lines.push("RewriteEngine On");
        lines.push(`RewriteCond %{HTTP_REFERER} !^$`);
        for (const domain of domains) {
          lines.push(`RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?${domain.replace(".", "\\.")}/ [NC]`);
        }
        lines.push("RewriteRule \\.(jpg|jpeg|png|gif|webp|svg)$ - [F,NC,L]");
        lines.push("");
      }
    }

    // CORS
    if (corsEnabled) {
      lines.push("# CORS Headers");
      lines.push(`Header set Access-Control-Allow-Origin "${corsOrigin}"`);
      lines.push("Header set Access-Control-Allow-Methods \"GET, POST, OPTIONS\"");
      lines.push("Header set Access-Control-Allow-Headers \"Content-Type\"");
      lines.push("");
    }

    // Gzip
    if (gzipEnabled) {
      lines.push("# Gzip Compression");
      lines.push("<IfModule mod_deflate.c>");
      lines.push("  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css");
      lines.push("  AddOutputFilterByType DEFLATE text/javascript application/javascript application/json");
      lines.push("  AddOutputFilterByType DEFLATE image/svg+xml application/xml");
      lines.push("</IfModule>");
      lines.push("");
    }

    // Browser caching
    if (cachingEnabled) {
      lines.push("# Browser Caching");
      lines.push("<IfModule mod_expires.c>");
      lines.push("  ExpiresActive On");
      lines.push(`  ExpiresByType image/jpg "access plus ${Math.floor(Number(cacheMaxAge) / 86400)} days"`);
      lines.push(`  ExpiresByType image/jpeg "access plus ${Math.floor(Number(cacheMaxAge) / 86400)} days"`);
      lines.push(`  ExpiresByType image/png "access plus ${Math.floor(Number(cacheMaxAge) / 86400)} days"`);
      lines.push(`  ExpiresByType image/webp "access plus ${Math.floor(Number(cacheMaxAge) / 86400)} days"`);
      lines.push(`  ExpiresByType text/css "access plus ${Math.floor(Number(cacheMaxAge) / 86400)} days"`);
      lines.push(`  ExpiresByType application/javascript "access plus ${Math.floor(Number(cacheMaxAge) / 86400)} days"`);
      lines.push("</IfModule>");
      lines.push(`<IfModule mod_headers.c>`);
      lines.push(`  Header set Cache-Control "max-age=${cacheMaxAge}, public"`);
      lines.push("</IfModule>");
      lines.push("");
    }

    // Block IPs
    const validIPs = blockedIPs.filter((b) => b.ip);
    if (validIPs.length > 0) {
      lines.push("# Block IPs");
      lines.push("<RequireAll>");
      lines.push("  Require all granted");
      for (const b of validIPs) {
        lines.push(`  Require not ip ${b.ip}`);
      }
      lines.push("</RequireAll>");
      lines.push("");
    }

    // Password protection
    if (passwordEnabled) {
      lines.push("# Password Protection");
      lines.push("AuthType Basic");
      lines.push(`AuthName "${authName}"`);
      lines.push(`AuthUserFile ${htpasswdPath}`);
      lines.push("Require valid-user");
      lines.push("");
    }

    return lines.join("\n").trim();
  };

  const output = generateHtaccess();

  const downloadFile = () => {
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = ".htaccess";
    a.click();
    URL.revokeObjectURL(url);
  };

  const inputClass =
    "px-3 py-2 text-sm border border-border-subtle rounded-lg bg-surface-raised text-text-primary focus:outline-none focus:ring-1 focus:ring-accent font-mono w-full";
  const toggleClass = (active: boolean) =>
    `px-3 py-1.5 text-xs rounded-lg font-medium transition-colors ${
      active
        ? "bg-accent text-white"
        : "bg-surface-raised border border-border-subtle text-text-secondary hover:border-accent"
    }`;

  const sectionClass = "bg-card-bg border border-card-border rounded-xl p-5 mb-4";
  const sectionTitle = "text-sm font-semibold text-text-primary mb-4 flex items-center gap-2";

  return (
    <ToolLayout
      agentReady
      title="htaccess Generator"
      description="Build Apache .htaccess configuration files visually. Configure redirects, rewrites, error pages, security settings, and more."
    >
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Configuration */}
        <div>
          {/* Force HTTPS */}
          <div className={sectionClass}>
            <div className={sectionTitle}>🔒 Force HTTPS</div>
            <div className="flex items-center gap-3">
              <button onClick={() => setForceHttps(!forceHttps)} className={toggleClass(forceHttps)}>
                {forceHttps ? "Enabled" : "Disabled"}
              </button>
              <span className="text-xs text-text-muted">Redirect all HTTP traffic to HTTPS</span>
            </div>
          </div>

          {/* www Mode */}
          <div className={sectionClass}>
            <div className={sectionTitle}>🌐 Force www / non-www</div>
            <div className="flex gap-2">
              {(["default", "www", "non-www"] as const).map((m) => (
                <button key={m} onClick={() => setWwwMode(m)} className={toggleClass(wwwMode === m)}>
                  {m === "default" ? "No redirect" : m === "www" ? "Force www" : "Force non-www"}
                </button>
              ))}
            </div>
          </div>

          {/* Redirects */}
          <div className={sectionClass}>
            <div className={sectionTitle}>↩️ Redirects</div>
            <div className="space-y-3">
              {redirects.map((r) => (
                <div key={r.id} className="flex items-center gap-2">
                  <select
                    value={r.type}
                    onChange={(e) => updateRedirect(r.id, "type", e.target.value)}
                    className="px-2 py-2 text-sm border border-border-subtle rounded-lg bg-surface-raised text-text-primary focus:outline-none focus:ring-1 focus:ring-accent font-mono w-20"
                  >
                    <option value="301">301</option>
                    <option value="302">302</option>
                  </select>
                  <input
                    placeholder="/old-path"
                    value={r.from}
                    onChange={(e) => updateRedirect(r.id, "from", e.target.value)}
                    className={inputClass + " flex-1"}
                  />
                  <span className="text-text-muted text-sm">→</span>
                  <input
                    placeholder="https://example.com/new"
                    value={r.to}
                    onChange={(e) => updateRedirect(r.id, "to", e.target.value)}
                    className={inputClass + " flex-1"}
                  />
                  <button onClick={() => removeRedirect(r.id)} className="text-text-muted hover:text-red-400 p-1">
                    <Trash2 size={14} />
                  </button>
                </div>
              ))}
              <button onClick={addRedirect} className="action-btn text-xs flex items-center gap-1.5">
                <Plus size={13} /> Add Redirect
              </button>
            </div>
          </div>

          {/* URL Rewriting */}
          <div className={sectionClass}>
            <div className={sectionTitle}>🔄 URL Rewriting</div>
            <div className="space-y-3">
              {rewriteRules.map((r) => (
                <div key={r.id} className="space-y-2">
                  <div className="flex items-center gap-2">
                    <input
                      placeholder="Pattern (e.g. ^blog/(.*)$)"
                      value={r.pattern}
                      onChange={(e) => updateRewriteRule(r.id, "pattern", e.target.value)}
                      className={inputClass + " flex-1"}
                    />
                    <span className="text-text-muted text-sm">→</span>
                    <input
                      placeholder="Substitution (e.g. /posts/$1)"
                      value={r.substitution}
                      onChange={(e) => updateRewriteRule(r.id, "substitution", e.target.value)}
                      className={inputClass + " flex-1"}
                    />
                    <input
                      placeholder="Flags"
                      value={r.flags}
                      onChange={(e) => updateRewriteRule(r.id, "flags", e.target.value)}
                      className="px-2 py-2 text-sm border border-border-subtle rounded-lg bg-surface-raised text-text-primary focus:outline-none focus:ring-1 focus:ring-accent font-mono w-16"
                    />
                    <button onClick={() => removeRewriteRule(r.id)} className="text-text-muted hover:text-red-400 p-1">
                      <Trash2 size={14} />
                    </button>
                  </div>
                </div>
              ))}
              <button onClick={addRewriteRule} className="action-btn text-xs flex items-center gap-1.5">
                <Plus size={13} /> Add Rule
              </button>
            </div>
          </div>

          {/* Error Pages */}
          <div className={sectionClass}>
            <div className={sectionTitle}>⚠️ Custom Error Pages</div>
            <div className="space-y-3">
              {errorPages.map((e) => (
                <div key={e.code} className="flex items-center gap-3">
                  <span className="font-mono text-sm text-accent w-10">{e.code}</span>
                  <input
                    placeholder={`/errors/${e.code}.html`}
                    value={e.path}
                    onChange={(ev) => updateErrorPage(e.code, ev.target.value)}
                    className={inputClass + " flex-1"}
                  />
                </div>
              ))}
            </div>
          </div>

          {/* Directory Listing */}
          <div className={sectionClass}>
            <div className={sectionTitle}>📁 Directory Listing</div>
            <div className="flex gap-2">
              {(["default", "enable", "disable"] as const).map((m) => (
                <button key={m} onClick={() => setDirectoryListing(m)} className={toggleClass(directoryListing === m)}>
                  {m === "default" ? "Default" : m === "enable" ? "Enable" : "Disable"}
                </button>
              ))}
            </div>
          </div>

          {/* Hotlink Protection */}
          <div className={sectionClass}>
            <div className={sectionTitle}>🔗 Hotlink Protection</div>
            <div className="flex items-center gap-3 mb-3">
              <button onClick={() => setHotlinkEnabled(!hotlinkEnabled)} className={toggleClass(hotlinkEnabled)}>
                {hotlinkEnabled ? "Enabled" : "Disabled"}
              </button>
            </div>
            {hotlinkEnabled && (
              <div className="space-y-2">
                <p className="text-xs text-text-muted mb-2">Allowed domains (won&apos;t be blocked):</p>
                {hotlinkDomains.map((d) => (
                  <div key={d.id} className="flex items-center gap-2">
                    <input
                      placeholder="example.com"
                      value={d.domain}
                      onChange={(e) => updateHotlinkDomain(d.id, e.target.value)}
                      className={inputClass + " flex-1"}
                    />
                    <button onClick={() => removeHotlinkDomain(d.id)} className="text-text-muted hover:text-red-400 p-1">
                      <Trash2 size={14} />
                    </button>
                  </div>
                ))}
                <button onClick={addHotlinkDomain} className="action-btn text-xs flex items-center gap-1.5">
                  <Plus size={13} /> Add Domain
                </button>
              </div>
            )}
          </div>

          {/* CORS */}
          <div className={sectionClass}>
            <div className={sectionTitle}>🌍 CORS Headers</div>
            <div className="flex items-center gap-3 mb-3">
              <button onClick={() => setCorsEnabled(!corsEnabled)} className={toggleClass(corsEnabled)}>
                {corsEnabled ? "Enabled" : "Disabled"}
              </button>
            </div>
            {corsEnabled && (
              <div className="flex items-center gap-3">
                <label className="text-xs text-text-secondary w-24">Allow-Origin</label>
                <input
                  value={corsOrigin}
                  onChange={(e) => setCorsOrigin(e.target.value)}
                  className={inputClass + " flex-1"}
                  placeholder="* or https://example.com"
                />
              </div>
            )}
          </div>

          {/* Gzip */}
          <div className={sectionClass}>
            <div className={sectionTitle}>⚡ Gzip Compression</div>
            <div className="flex items-center gap-3">
              <button onClick={() => setGzipEnabled(!gzipEnabled)} className={toggleClass(gzipEnabled)}>
                {gzipEnabled ? "Enabled" : "Disabled"}
              </button>
              <span className="text-xs text-text-muted">Compress HTML, CSS, JS, and more</span>
            </div>
          </div>

          {/* Browser Caching */}
          <div className={sectionClass}>
            <div className={sectionTitle}>💾 Browser Caching</div>
            <div className="flex items-center gap-3 mb-3">
              <button onClick={() => setCachingEnabled(!cachingEnabled)} className={toggleClass(cachingEnabled)}>
                {cachingEnabled ? "Enabled" : "Disabled"}
              </button>
            </div>
            {cachingEnabled && (
              <div className="flex items-center gap-3">
                <label className="text-xs text-text-secondary w-24">Max Age (sec)</label>
                <select
                  value={cacheMaxAge}
                  onChange={(e) => setCacheMaxAge(e.target.value)}
                  className="px-3 py-2 text-sm border border-border-subtle rounded-lg bg-surface-raised text-text-primary focus:outline-none focus:ring-1 focus:ring-accent font-mono"
                >
                  <option value="86400">1 day</option>
                  <option value="604800">1 week</option>
                  <option value="2592000">30 days</option>
                  <option value="31536000">1 year</option>
                </select>
              </div>
            )}
          </div>

          {/* Block IPs */}
          <div className={sectionClass}>
            <div className={sectionTitle}>🚫 Block IPs</div>
            <div className="space-y-2">
              {blockedIPs.map((b) => (
                <div key={b.id} className="flex items-center gap-2">
                  <input
                    placeholder="192.168.1.1 or 10.0.0.0/8"
                    value={b.ip}
                    onChange={(e) => updateBlockedIP(b.id, e.target.value)}
                    className={inputClass + " flex-1"}
                  />
                  <button onClick={() => removeBlockedIP(b.id)} className="text-text-muted hover:text-red-400 p-1">
                    <Trash2 size={14} />
                  </button>
                </div>
              ))}
              <button onClick={addBlockedIP} className="action-btn text-xs flex items-center gap-1.5">
                <Plus size={13} /> Block IP
              </button>
            </div>
          </div>

          {/* Password Protection */}
          <div className={sectionClass}>
            <div className={sectionTitle}>🔑 Password Protection</div>
            <div className="flex items-center gap-3 mb-3">
              <button onClick={() => setPasswordEnabled(!passwordEnabled)} className={toggleClass(passwordEnabled)}>
                {passwordEnabled ? "Enabled" : "Disabled"}
              </button>
            </div>
            {passwordEnabled && (
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <label className="text-xs text-text-secondary w-28">Auth Name</label>
                  <input
                    value={authName}
                    onChange={(e) => setAuthName(e.target.value)}
                    className={inputClass + " flex-1"}
                  />
                </div>
                <div className="flex items-center gap-3">
                  <label className="text-xs text-text-secondary w-28">.htpasswd Path</label>
                  <input
                    value={htpasswdPath}
                    onChange={(e) => setHtpasswdPath(e.target.value)}
                    className={inputClass + " flex-1"}
                  />
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Right: Output */}
        <div className="lg:sticky lg:top-4 h-fit">
          <div className="bg-card-bg border border-card-border rounded-xl overflow-hidden">
            <div className="flex items-center justify-between px-4 py-3 border-b border-border-subtle bg-surface-subtle">
              <span className="text-sm font-semibold text-text-primary font-mono">.htaccess</span>
              <div className="flex gap-2">
                <CopyButton text={output} label="Copy" />
                <button onClick={downloadFile} className="action-btn text-xs">
                  Download
                </button>
              </div>
            </div>
            <pre className="p-4 text-xs font-mono text-text-primary overflow-auto max-h-[600px] leading-relaxed whitespace-pre-wrap">
              {output || "# Configure options on the left to generate your .htaccess file"}
            </pre>
          </div>
        </div>
      </div>
    </ToolLayout>
  );
}
