export type ToolSize = "featured" | "medium" | "standard";
export type ToolCategory =
  | "FORMAT & VALIDATE"
  | "ENCODE & DECODE"
  | "CONVERT"
  | "GENERATE"
  | "NETWORK"
  | "COMPARE"
  | "TEST & DEBUG"
  | "PDF"
  | "SEO";

export interface Tool {
  id: string;
  name: string;
  description: string;
  route: string;
  /** Search tags for fuzzy matching */
  tags?: string[];
  category: ToolCategory;
  size: ToolSize;
  icon: string;
  preview?: string;
  live?: boolean;
  /** Monthly search volume (from Semrush, used for treemap sizing) */
  volume?: number;
  /** CPC in USD (from Semrush, used for treemap heat coloring) */
  cpc?: number;
  /** Month-over-month trend: up, down, or flat */
  trend?: "up" | "down" | "flat";
}

export const tools: Tool[] = [
  // FORMAT & VALIDATE
  {
    id: "json",
    name: "JSON Formatter",
    description: "Format, validate & minify JSON",
    route: "/json-formatter",
    category: "FORMAT & VALIDATE",
    size: "featured",
    icon: "Braces",
    preview: '{\n  "name": "devpick",\n  "tools": 20\n}',
    volume: 90500,
    cpc: 6.41, trend: "up" as const,
  },
  {
    id: "sql",
    name: "SQL Formatter",
    description: "Beautify SQL queries",
    route: "/sql-formatter",
    category: "FORMAT & VALIDATE",
    size: "standard",
    icon: "Database",
    preview: "SELECT * FROM users",
    volume: 12100,
    cpc: 2.85, trend: "flat" as const,
  },
  {
    id: "xml",
    name: "XML Formatter",
    description: "Format & validate XML documents",
    route: "/xml-formatter",
    category: "FORMAT & VALIDATE",
    size: "standard",
    icon: "Code2",
    preview: "<root><item/></root>",
    volume: 22200,
    cpc: 2.29, trend: "up" as const,
  },
  // ENCODE & DECODE
  {
    id: "base64",
    name: "Base64",
    description: "Encode & decode Base64",
    tags: ["base64", "encode", "decode", "binary"],
    route: "/base64",
    category: "ENCODE & DECODE",
    size: "medium",
    icon: "Binary",
    preview: "hello world → aGVsbG8gd29ybGQ=",
    volume: 40500,
    cpc: 2.46, trend: "up" as const,
  },
  {
    id: "url",
    name: "URL Encoder",
    description: "Encode & decode URL components",
    route: "/url-encoder",
    category: "ENCODE & DECODE",
    size: "standard",
    icon: "Link",
    preview: "hello world → hello%20world",
    volume: 14800,
    cpc: 1.5, trend: "down" as const,
  },
  {
    id: "html-entities",
    name: "HTML Entities",
    description: "Encode & decode HTML entities",
    tags: ["html", "entities", "encode", "decode", "escape", "ampersand"],
    route: "/html-entities",
    category: "ENCODE & DECODE",
    size: "standard",
    icon: "FileCode",
    preview: "<div> → &lt;div&gt;",
    volume: 3600,
    cpc: 0.5, trend: "flat" as const,
  },
  {
    id: "jwt",
    name: "JWT Decoder",
    description: "Decode & inspect JWT tokens",
    route: "/jwt-decoder",
    category: "ENCODE & DECODE",
    size: "medium",
    icon: "KeyRound",
    preview: '{ "alg": "HS256", "typ": "JWT" }',
    volume: 5400,
    cpc: 0.0, trend: "up" as const,
  },
  // CONVERT
  {
    id: "timestamp",
    name: "Unix Timestamp Converter",
    description: "Convert unix/epoch timestamps to dates",
    route: "/unix-timestamp-converter",
    category: "CONVERT",
    size: "medium",
    icon: "Clock",
    preview: "live",
    live: true,
    volume: 18100,
    cpc: 2.04, trend: "up" as const,
  },
  {
    id: "yaml",
    name: "YAML to JSON",
    description: "Convert YAML to JSON and back",
    route: "/yaml-formatter",
    category: "CONVERT",
    size: "standard",
    icon: "ArrowLeftRight",
    preview: "key: value → {key: value}",
    volume: 3600,
    cpc: 1.0, trend: "down" as const,
  },
  {
    id: "base-converter",
    name: "Number Base",
    description: "Convert between number bases",
    tags: ["base", "number", "binary", "hex", "octal", "decimal", "convert"],
    route: "/base",
    category: "CONVERT",
    size: "standard",
    icon: "Hash",
    preview: "255 → 0xFF → 0b11111111",
    volume: 2900,
    cpc: 0.3, trend: "flat" as const,
  },
  {
    id: "csv",
    name: "CSV to JSON",
    description: "Convert CSV data to JSON",
    route: "/csv-formatter",
    category: "CONVERT",
    size: "medium",
    icon: "Table",
    preview: 'name,age\nAlice,30 → [{"name":"Alice"}]',
    volume: 8100,
    cpc: 4.44, trend: "up" as const,
  },
  // GENERATE
  {
    id: "uuid",
    name: "UUID Generator",
    description: "Generate UUIDs v4",
    route: "/uuid-generator",
    category: "GENERATE",
    size: "standard",
    icon: "Fingerprint",
    preview: "xxxxxxxx-xxxx-4xxx-yxxx",
    volume: 18100,
    cpc: 0.07, trend: "up" as const,
  },
  {
    id: "hash",
    name: "Hash Generator",
    description: "MD5, SHA-1, SHA-256, SHA-512",
    route: "/hash-generator",
    category: "GENERATE",
    size: "medium",
    icon: "ShieldCheck",
    preview: "hello → 5d41402abc4b...",
    volume: 4400,
    cpc: 0.0, trend: "flat" as const,
  },
  {
    id: "password",
    name: "Password Generator",
    description: "Generate strong random passwords",
    route: "/password-generator",
    category: "GENERATE",
    size: "standard",
    icon: "Lock",
    preview: "xK#9mP$2nQ@1",
    volume: 74000,
    cpc: 0.05, trend: "up" as const,
  },
  {
    id: "lorem",
    name: "Lorem Ipsum",
    description: "Generate placeholder text",
    route: "/lorem-ipsum-generator",
    category: "GENERATE",
    size: "standard",
    icon: "AlignLeft",
    preview: "Lorem ipsum dolor sit...",
    volume: 6600,
    cpc: 0.1, trend: "down" as const,
  },
  // CONVERT (new)
  {
    id: "timezone",
    name: "Timezone Converter",
    description: "Convert time between IANA timezones",
    tags: ["timezone", "time", "convert", "utc", "gmt"],
    route: "/timezone",
    category: "CONVERT",
    size: "medium",
    icon: "Globe2",
    preview: "EST → JST · KST · CET",
    live: true,
    volume: 8100,
    cpc: 0.5, trend: "up" as const,
  },
  {
    id: "color",
    name: "Color Picker",
    description: "Convert HEX ↔ RGB ↔ HSL",
    route: "/color-picker",
    category: "CONVERT",
    size: "medium",
    icon: "Palette",
    preview: "#3b82f6 → rgb(59,130,246)",
    volume: 201000,
    cpc: 1.41, trend: "up" as const,
  },
  // FORMAT & VALIDATE (new)
  {
    id: "case",
    name: "Case Converter",
    description: "camelCase, snake_case, PascalCase & more",
    route: "/case-converter",
    category: "FORMAT & VALIDATE",
    size: "standard",
    icon: "CaseSensitive",
    preview: "helloWorld → hello_world",
    volume: 2400,
    cpc: 0.2, trend: "flat" as const,
  },
  {
    id: "counter",
    name: "Word Counter",
    description: "Characters, words, sentences, reading time",
    route: "/character-counter",
    category: "FORMAT & VALIDATE",
    size: "standard",
    icon: "LetterText",
    preview: "128 words · 4 min read",
    volume: 201000,
    cpc: 0.03, trend: "up" as const,
  },
  {
    id: "markdown",
    name: "Markdown Preview",
    description: "Live Markdown editor & renderer",
    route: "/markdown-preview",
    category: "FORMAT & VALIDATE",
    size: "medium",
    icon: "FileText",
    preview: "# Heading\n**bold** *italic*",
    volume: 27100,
    cpc: 0.5, trend: "down" as const,
  },
  // GENERATE (new)
  {
    id: "qr",
    name: "QR Code Generator",
    description: "Generate QR codes from text or URLs",
    route: "/qr-code-generator",
    category: "GENERATE",
    size: "medium",
    icon: "QrCode",
    preview: "devpick.sh → ▓▓▓▓▓",
    volume: 823000,
    cpc: 1.46, trend: "up" as const,
  },
  // NETWORK
  {
    id: "subnet",
    name: "Subnet Calculator",
    description: "CIDR subnet calculations",
    route: "/subnet",
    category: "NETWORK",
    size: "featured",
    icon: "Network",
    preview: "192.168.1.0/24 → 254 hosts",
    volume: 49500,
    cpc: 5.36, trend: "down" as const,
  },
  {
    id: "ip-lookup",
    name: "IP Lookup",
    description: "Look up IP address info",
    tags: ["ip", "address", "lookup", "geolocation", "whois"],
    route: "/ip-lookup",
    category: "NETWORK",
    size: "standard",
    icon: "Globe",
    preview: "Your IP: fetching...",
    volume: 110000,
    cpc: 0.5, trend: "up" as const,
  },
  // COMPARE
  {
    id: "diff",
    name: "Diff Checker",
    description: "Compare text side by side",
    route: "/diff-checker",
    category: "COMPARE",
    size: "medium",
    icon: "GitCompare",
    preview: "+ added line\n- removed line",
    volume: 27100,
    cpc: 1.51, trend: "up" as const,
  },
  // CONVERT (new)
  {
    id: "hex-rgb",
    name: "Hex ↔ RGB",
    description: "Convert hex colors to RGB/HSL and back",
    tags: ["hex", "rgb", "color", "convert"],
    route: "/hex-rgb",
    category: "CONVERT",
    size: "standard",
    icon: "Pipette",
    preview: "#ff5733 → rgb(255,87,51)",
    volume: 8100,
    cpc: 0.87, trend: "flat" as const,
  },
  {
    id: "ascii",
    name: "ASCII Table",
    description: "Full ASCII table with search & copy",
    route: "/ascii-art-generator",
    category: "CONVERT",
    size: "standard",
    icon: "TableProperties",
    preview: "A = 65 = 0x41 = 0o101",
    volume: 12100,
    cpc: 0.3, trend: "down" as const,
  },
  {
    id: "toml",
    name: "TOML to JSON",
    description: "Convert TOML to JSON and back",
    tags: ["toml", "validate", "config", "format"],
    route: "/toml",
    category: "CONVERT",
    size: "standard",
    icon: "FileCode2",
    preview: "[server]\nhost = localhost",
    volume: 1000,
    cpc: 0.5, trend: "flat" as const,
  },
  // TEST & DEBUG (new)
  {
    id: "jsonpath",
    name: "JSONPath Tester",
    description: "Test JSONPath expressions against JSON",
    tags: ["jsonpath", "json", "query", "filter", "expression"],
    route: "/jsonpath",
    category: "TEST & DEBUG",
    size: "standard",
    icon: "Locate",
    preview: "$.store.book[*].title",
    volume: 2400,
    cpc: 0.5, trend: "up" as const,
  },
  // FORMAT & VALIDATE (new)
  {
    id: "number-format",
    name: "Number Formatter",
    description: "Format numbers as commas, currency, binary, words…",
    tags: ["number", "format", "comma", "currency"],
    route: "/number-format",
    category: "FORMAT & VALIDATE",
    size: "standard",
    icon: "Hash",
    preview: "1234567 → 1,234,567",
    volume: 1600,
    cpc: 0.2, trend: "down" as const,
  },
  // CONVERT (new — batch 2)
  {
    id: "json-to-ts",
    name: "JSON → TypeScript",
    description: "Convert JSON to TypeScript interfaces",
    tags: ["json", "typescript", "type", "interface", "generate"],
    route: "/json-to-ts",
    category: "CONVERT",
    size: "medium",
    icon: "FileJson",
    preview: '{"name":"Alice"} → interface Root',
    volume: 14800,
    cpc: 1.99, trend: "up" as const,
  },
  // FORMAT & VALIDATE (new — batch 2)
  {
    id: "minify",
    name: "Code Minifier",
    description: "Minify HTML, CSS, and JavaScript",
    route: "/js-minifier",
    category: "FORMAT & VALIDATE",
    size: "standard",
    icon: "Minimize2",
    preview: "<div>  </div> → <div></div>",
    volume: 6600,
    cpc: 0.5, trend: "down" as const,
  },
  // ENCODE & DECODE (new — batch 2)
  {
    id: "escape",
    name: "Escape / Unescape",
    description: "Escape JSON, HTML, URL, XML, Regex",
    tags: ["escape", "unescape", "string", "special characters"],
    route: "/escape",
    category: "ENCODE & DECODE",
    size: "standard",
    icon: "Shield",
    preview: "<div> → &lt;div&gt;",
    volume: 3600,
    cpc: 0.3, trend: "flat" as const,
  },
  {
    id: "image-base64",
    name: "Image → Base64",
    description: "Convert images to Base64 data URIs",
    tags: ["image", "base64", "encode", "data uri", "embed"],
    route: "/image-base64",
    category: "ENCODE & DECODE",
    size: "standard",
    icon: "Image",
    preview: "PNG → data:image/png;base64,...",
    volume: 2400,
    cpc: 0.5, trend: "up" as const,
  },
  // GENERATE (new — batch 2)
  {
    id: "slug",
    name: "Slug Generator",
    description: "Generate URL-safe slugs from text",
    route: "/slug-generator",
    category: "GENERATE",
    size: "standard",
    icon: "Link2",
    preview: "Hello World → hello-world",
    volume: 4400,
    cpc: 0.3, trend: "flat" as const,
  },
  // NETWORK (new — batch 2)
  {
    id: "chmod",
    name: "Chmod Calculator",
    description: "Calculate Unix file permissions",
    tags: ["chmod", "permissions", "unix", "linux", "file"],
    route: "/chmod",
    category: "NETWORK",
    size: "standard",
    icon: "Terminal",
    preview: "755 → rwxr-xr-x",
    volume: 8100,
    cpc: 0.2, trend: "up" as const,
  },
  // GENERATE (batch 3)
  {
    id: "robots-txt",
    name: "Robots.txt Generator",
    description: "Generate robots.txt with user agents, paths, and sitemap",
    tags: ["robots", "txt", "seo", "crawl", "spider", "sitemap"],
    route: "/robots-txt",
    category: "SEO",
    size: "standard",
    icon: "Shield",
    preview: "User-agent: *\nDisallow: /admin/",
    volume: 1000,
    cpc: 3.10, trend: "up" as const,
  },
  {
    id: "meta-tags",
    name: "Meta Tag Generator",
    description: "Generate meta, Open Graph, and Twitter Card tags",
    tags: ["meta", "tags", "seo", "html", "head", "og", "title", "description"],
    route: "/meta-tags",
    category: "SEO",
    size: "standard",
    icon: "FileCode",
    preview: "<meta property=\"og:title\" ... />",
    volume: 6000,
    cpc: 2.50, trend: "up" as const,
  },
  {
    id: "css-gradient",
    name: "CSS Gradient Generator",
    description: "Generate linear, radial, and conic CSS gradients",
    tags: ["css", "gradient", "linear", "radial", "background"],
    route: "/css-gradient",
    category: "GENERATE",
    size: "medium",
    icon: "Palette",
    preview: "linear-gradient(90deg, #3b82f6, #8b5cf6)",
    volume: 33000,
    cpc: 1.20, trend: "up" as const,
  },
  {
    id: "css-box-shadow",
    name: "Box Shadow Generator",
    description: "Generate CSS box shadows with live preview",
    tags: ["css", "box shadow", "shadow", "elevation"],
    route: "/css-box-shadow",
    category: "GENERATE",
    size: "standard",
    icon: "Layers",
    preview: "box-shadow: 0 4px 12px rgba(0,0,0,.15)",
    volume: 22000,
    cpc: 0.90, trend: "up" as const,
  },
  {
    id: "css-border-radius",
    name: "Border Radius Generator",
    description: "Generate CSS border-radius with individual corners",
    tags: ["css", "border radius", "rounded", "corners"],
    route: "/css-border-radius",
    category: "GENERATE",
    size: "standard",
    icon: "Square",
    preview: "border-radius: 8px 16px 8px 16px",
    volume: 3000,
    cpc: 0.50, trend: "flat" as const,
  },
  {
    id: "css-grid",
    name: "CSS Grid Generator",
    description: "Build CSS Grid layouts with columns, rows, and gap",
    tags: ["css", "grid", "layout", "template", "columns", "rows"],
    route: "/css-grid",
    category: "GENERATE",
    size: "standard",
    icon: "LayoutGrid",
    preview: "grid-template-columns: 1fr 1fr 1fr",
    volume: 9000,
    cpc: 0.70, trend: "up" as const,
  },
  {
    id: "flexbox",
    name: "Flexbox Playground",
    description: "Interactive CSS Flexbox builder with live preview",
    tags: ["css", "flexbox", "layout", "align", "justify"],
    route: "/flexbox",
    category: "GENERATE",
    size: "medium",
    icon: "Columns2",
    preview: "display: flex; justify-content: center",
    volume: 14000,
    cpc: 0.80, trend: "up" as const,
  },
  // NETWORK (batch 3)
  {
    id: "http-status",
    name: "HTTP Status Codes",
    description: "Complete reference for all HTTP status codes",
    tags: ["http", "status", "code", "response", "error", "api"],
    route: "/http-status",
    category: "NETWORK",
    size: "medium",
    icon: "Globe",
    preview: "200 OK · 404 Not Found · 500 Error",
    volume: 12000,
    cpc: 0.30, trend: "up" as const,
  },
  // GENERATE (Phase 3 high-volume)
  {
    id: "barcode",
    name: "Barcode Generator",
    description: "Generate Code 128, EAN-13, Code 39 barcodes",
    route: "/barcode-generator",
    category: "GENERATE",
    size: "featured",
    icon: "BarChart3",
    preview: "DEVPICK → ▎▏▎▎▎▏▎",
    volume: 301000,
    cpc: 1.46, trend: "up" as const,
  },
  // CONVERT (Phase 3 high-volume)
  {
    id: "webp-to-png",
    name: "WebP to PNG",
    description: "Convert WebP images to PNG format",
    tags: ["webp", "png", "convert", "image"],
    route: "/webp-to-png",
    category: "CONVERT",
    size: "medium",
    icon: "ImageDown",
    preview: "image.webp → image.png",
    volume: 165000,
    cpc: 2.84, trend: "flat" as const,
  },
  {
    id: "color-from-image",
    name: "Color Picker from Image",
    description: "Click image pixels to get HEX, RGB, HSL",
    route: "/color-from-image",
    category: "CONVERT",
    size: "medium",
    icon: "Pipette",
    preview: "click → #3b82f6 · rgb(59,130,246)",
    volume: 40500,
    cpc: 0.87, trend: "up" as const,
  },
  {
    id: "aspect-ratio",
    name: "Aspect Ratio Calculator",
    description: "Calculate & scale aspect ratios",
    tags: ["aspect ratio", "resolution", "video", "image", "calculate"],
    route: "/aspect-ratio",
    category: "CONVERT",
    size: "standard",
    icon: "Crop",
    preview: "1920×1080 → 16:9",
    volume: 8000,
    cpc: 0.50, trend: "up" as const,
  },
  // GENERATE (Phase 3 continued)
  {
    id: "color-palette",
    name: "Color Palette Generator",
    description: "Generate complementary, analogous & triadic palettes",
    tags: ["color", "palette", "scheme", "complementary", "harmony"],
    route: "/color-palette",
    category: "GENERATE",
    size: "medium",
    icon: "Palette",
    preview: "#3b82f6 → 5-color palette",
    volume: 8000,
    cpc: 1.00, trend: "up" as const,
  },
  {
    id: "favicon",
    name: "Favicon Generator",
    description: "Generate favicons at 16, 32, 48, 180px from image or text",
    route: "/favicon-generator",
    category: "GENERATE",
    size: "standard",
    icon: "Star",
    preview: "🚀 → favicon.ico",
    volume: 12100,
    cpc: 2.08, trend: "flat" as const,
  },
  // CONVERT (Phase 4)
  {
    id: "mp4-to-mp3",
    name: "MP4 to Audio",
    description: "Extract audio from MP4 and video files",
    tags: ["mp4", "mp3", "audio", "video", "extract", "convert"],
    route: "/mp4-to-mp3",
    category: "CONVERT",
    size: "featured",
    icon: "Music",
    preview: "video.mp4 → audio.webm",
    volume: 135000,
    cpc: 0.03, trend: "up" as const,
  },
  // GENERATE (Phase 4)
  {
    id: "invoice",
    name: "Invoice Generator",
    description: "Create professional invoices and download as PDF",
    route: "/invoice-generator",
    category: "GENERATE",
    size: "medium",
    icon: "Receipt",
    preview: "Company → Client $1,500.00",
    volume: 6600,
    cpc: 5.38, trend: "up" as const,
  },
  // FORMAT & VALIDATE (Phase 4)
  {
    id: "text-sort",
    name: "Text Sort & Dedupe",
    description: "Sort lines, deduplicate, trim whitespace",
    tags: ["sort", "dedupe", "unique", "lines", "alphabetical"],
    route: "/text-sort",
    category: "FORMAT & VALIDATE",
    size: "standard",
    icon: "ArrowUpDown",
    preview: "banana, apple → apple, banana",
    volume: 3000,
    cpc: 0.30, trend: "flat" as const,
  },
  // CONVERT (Phase 4)
  {
    id: "html-to-markdown",
    name: "HTML to Markdown",
    description: "Convert HTML to Markdown format",
    tags: ["html", "markdown", "convert", "markup"],
    route: "/html-to-markdown",
    category: "CONVERT",
    size: "standard",
    icon: "FileDown",
    preview: "<h1>Hi</h1> → # Hi",
    volume: 5000,
    cpc: 0.50, trend: "up" as const,
  },
  // TEST & DEBUG (Phase 4)
  {
    id: "json-schema",
    name: "JSON Schema Validator",
    description: "Validate JSON data against JSON Schema",
    tags: ["json", "schema", "validate", "draft"],
    route: "/json-schema",
    category: "TEST & DEBUG",
    size: "medium",
    icon: "CheckSquare",
    preview: '{"type":"object"} → ✓ valid',
    volume: 4000,
    cpc: 0.50, trend: "up" as const,
  },
  // CONVERT (Phase 4)
  {
    id: "text-to-binary",
    name: "Text to Binary",
    description: "Convert text to binary, hex, octal, decimal",
    tags: ["text", "binary", "convert", "ascii"],
    route: "/text-to-binary",
    category: "CONVERT",
    size: "standard",
    icon: "Binary",
    preview: "Hello → 01001000...",
    volume: 2000,
    cpc: 0.20, trend: "flat" as const,
  },
  // ─── New Batch: Formatters ───
  {
    id: "css-formatter",
    name: "CSS Formatter",
    description: "Beautify & minify CSS code",
    tags: ["css", "format", "prettify", "beautify", "stylesheet"],
    route: "/css-formatter",
    category: "FORMAT & VALIDATE",
    size: "standard",
    icon: "Paintbrush",
    volume: 8100,
    cpc: 2.50, trend: "flat" as const,
  },
  {
    id: "html-formatter",
    name: "HTML Formatter",
    description: "Beautify & minify HTML",
    tags: ["html", "format", "prettify", "beautify", "markup"],
    route: "/html-formatter",
    category: "FORMAT & VALIDATE",
    size: "standard",
    icon: "FileCode",
    volume: 6600,
    cpc: 2.10, trend: "flat" as const,
  },
  {
    id: "js-formatter",
    name: "JS/TS Formatter",
    description: "Beautify & minify JavaScript and TypeScript",
    tags: ["javascript", "js", "typescript", "ts", "format", "prettify"],
    route: "/js-formatter",
    category: "FORMAT & VALIDATE",
    size: "standard",
    icon: "FileJson2",
    volume: 5400,
    cpc: 2.80, trend: "up" as const,
  },
  {
    id: "json-viewer",
    name: "JSON Viewer",
    description: "Interactive JSON tree viewer with search & path copy",
    tags: ["json", "viewer", "tree", "explore", "browse"],
    route: "/json-viewer",
    category: "FORMAT & VALIDATE",
    size: "medium",
    icon: "TreePine",
    volume: 22200,
    cpc: 4.73, trend: "up" as const,
  },
  // ─── New Batch: Converters ───
  {
    id: "xml-to-json",
    name: "XML to JSON",
    description: "Convert XML documents to JSON",
    tags: ["xml", "json", "convert", "transform"],
    route: "/xml-to-json",
    category: "CONVERT",
    size: "standard",
    icon: "ArrowRightLeft",
    volume: 4400,
    cpc: 1.90, trend: "flat" as const,
  },
  {
    id: "json-to-yaml",
    name: "JSON to YAML",
    description: "Convert between JSON and YAML",
    tags: ["json", "yaml", "convert", "transform"],
    route: "/json-to-yaml",
    category: "CONVERT",
    size: "standard",
    icon: "ArrowRightLeft",
    volume: 3600,
    cpc: 1.50, trend: "up" as const,
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV data to JSON",
    tags: ["csv", "json", "convert", "spreadsheet", "parse"],
    route: "/csv-to-json",
    category: "CONVERT",
    size: "standard",
    icon: "Table",
    volume: 3200,
    cpc: 1.99, trend: "up" as const,
  },
  {
    id: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Convert Markdown to HTML",
    tags: ["markdown", "html", "convert", "render"],
    route: "/markdown-to-html",
    category: "CONVERT",
    size: "standard",
    icon: "FileDown",
    volume: 2900,
    cpc: 1.20, trend: "flat" as const,
  },
  {
    id: "png-to-jpg",
    name: "PNG to JPG",
    description: "Convert PNG images to JPG format",
    tags: ["png", "jpg", "convert", "image"],
    route: "/png-to-jpg",
    category: "CONVERT",
    size: "medium",
    icon: "Image",
    volume: 49500,
    cpc: 0.31, trend: "up" as const,
  },
  {
    id: "image-resize",
    name: "Image Resize",
    description: "Resize images by dimensions or percentage",
    tags: ["image", "resize", "scale", "dimensions", "width", "height"],
    route: "/image-resize",
    category: "CONVERT",
    size: "standard",
    icon: "Maximize2",
    volume: 22200,
    cpc: 0.80, trend: "up" as const,
  },
  {
    id: "image-compress",
    name: "Image Compress",
    description: "Compress images by adjusting quality",
    tags: ["image", "compress", "optimize", "reduce", "size", "jpg", "png"],
    route: "/image-compress",
    category: "CONVERT",
    size: "standard",
    icon: "Minimize2",
    volume: 22200,
    cpc: 0.91, trend: "up" as const,
  },
  {
    id: "svg-to-png",
    name: "SVG to PNG",
    description: "Convert SVG files to PNG images",
    tags: ["svg", "png", "convert", "raster", "vector"],
    route: "/svg-to-png",
    category: "CONVERT",
    size: "standard",
    icon: "Image",
    volume: 8100,
    cpc: 1.20, trend: "flat" as const,
  },
  // ─── New Batch: Encode/Decode ───
  {
    id: "binary-to-text",
    name: "Binary to Text",
    description: "Decode binary, hex, octal back to text",
    tags: ["binary", "text", "convert", "decode"],
    route: "/binary-to-text",
    category: "ENCODE & DECODE",
    size: "standard",
    icon: "Binary",
    volume: 2400,
    cpc: 0.50, trend: "flat" as const,
  },
  {
    id: "text-to-hex",
    name: "Text to Hex",
    description: "Encode & decode text to hexadecimal",
    tags: ["text", "hex", "hexadecimal", "convert"],
    route: "/text-to-hex",
    category: "ENCODE & DECODE",
    size: "standard",
    icon: "Hash",
    volume: 1900,
    cpc: 0.40, trend: "flat" as const,
  },
  // ─── New Batch: Test & Debug ───
  {
    id: "og-preview",
    name: "Open Graph Preview",
    description: "Preview social media share cards from meta tags",
    tags: ["og", "open graph", "social", "preview", "twitter", "facebook", "seo"],
    route: "/og-preview",
    category: "SEO",
    size: "standard",
    icon: "Share2",
    volume: 4400,
    cpc: 2.10, trend: "up" as const,
  },
  // ─── New Batch: Generate ───
  {
    id: "email-template",
    name: "Email Template Builder",
    description: "Build HTML email templates with visual editor",
    tags: ["email", "template", "html", "newsletter"],
    route: "/email-template",
    category: "GENERATE",
    size: "standard",
    icon: "Mail",
    volume: 590,
    cpc: 10.77, trend: "up" as const,
  },
  // ─── PDF Tools ───
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages to JPG images",
    tags: ["pdf", "jpg", "jpeg", "image", "convert", "export"],
    route: "/pdf-to-jpg",
    category: "PDF",
    size: "featured",
    icon: "FileText",
    volume: 165000,
    cpc: 0.16, trend: "up" as const,
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert images to a PDF document",
    tags: ["jpg", "jpeg", "image", "pdf", "convert", "photo"],
    route: "/jpg-to-pdf",
    category: "PDF",
    size: "featured",
    icon: "FileText",
    volume: 165000,
    cpc: 0.31, trend: "up" as const,
  },
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDFs into one file",
    tags: ["pdf", "merge", "combine", "join", "concatenate"],
    route: "/merge-pdf",
    category: "PDF",
    size: "featured",
    icon: "FileText",
    volume: 135000,
    cpc: 0.48, trend: "up" as const,
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size by optimizing structure",
    tags: ["pdf", "compress", "reduce", "shrink", "optimize", "size"],
    route: "/compress-pdf",
    category: "PDF",
    size: "medium",
    icon: "FileText",
    volume: 110000,
    cpc: 0.42, trend: "up" as const,
  },
  {
    id: "word-to-pdf",
    name: "Text to PDF",
    description: "Convert text files to a PDF document",
    tags: ["word", "text", "txt", "pdf", "document", "convert"],
    route: "/word-to-pdf",
    category: "PDF",
    size: "medium",
    icon: "FileText",
    volume: 110000,
    cpc: 0.20, trend: "up" as const,
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    description: "Split a PDF into individual pages or ranges",
    tags: ["pdf", "split", "extract", "separate", "pages"],
    route: "/split-pdf",
    category: "PDF",
    size: "medium",
    icon: "FileText",
    volume: 33000,
    cpc: 0.54, trend: "up" as const,
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password protection from PDF files",
    tags: ["pdf", "unlock", "password", "remove", "decrypt"],
    route: "/unlock-pdf",
    category: "PDF",
    size: "medium",
    icon: "FileText",
    volume: 12100,
    cpc: 1.10, trend: "flat" as const,
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate PDF pages clockwise or counter-clockwise",
    tags: ["pdf", "rotate", "orientation", "landscape", "portrait"],
    route: "/rotate-pdf",
    category: "PDF",
    size: "medium",
    icon: "FileText",
    volume: 8100,
    cpc: 0.18, trend: "flat" as const,
  },
  {
    id: "pdf-page-remover",
    name: "PDF Page Remover",
    description: "Delete specific pages from a PDF",
    tags: ["pdf", "remove", "delete", "pages"],
    route: "/pdf-page-remover",
    category: "PDF",
    size: "medium",
    icon: "FileText",
    volume: 5000,
    cpc: 0.30, trend: "flat" as const,
  },
  {
    id: "pdf-watermark",
    name: "PDF Watermark",
    description: "Add text watermark to every PDF page",
    tags: ["pdf", "watermark", "stamp", "text", "overlay"],
    route: "/pdf-watermark",
    category: "PDF",
    size: "medium",
    icon: "FileText",
    volume: 3000,
    cpc: 0.25, trend: "flat" as const,
  },
  // ─── New Batch: Tier S ───
  {
    id: "csv-to-sql",
    name: "CSV to SQL",
    description: "Convert CSV to CREATE TABLE + INSERT statements",
    tags: ["csv", "sql", "database", "insert", "create table", "convert"],
    route: "/csv-to-sql",
    category: "CONVERT",
    size: "standard",
    icon: "Database",
    preview: "name,age → INSERT INTO...",
    volume: 390,
    cpc: 5.86, trend: "up" as const,
  },
  {
    id: "csv-viewer",
    name: "CSV Viewer",
    description: "View and sort CSV data as an interactive table",
    tags: ["csv", "viewer", "table", "spreadsheet", "data"],
    route: "/csv-viewer",
    category: "FORMAT & VALIDATE",
    size: "medium",
    icon: "Table",
    preview: "CSV → sortable table",
    volume: 1000,
    cpc: 2.89, trend: "up" as const,
  },
  {
    id: "webhook-tester",
    name: "Webhook Request Builder",
    description: "Build HTTP requests with custom headers and body",
    tags: ["webhook", "http", "request", "api", "post", "get", "curl"],
    route: "/webhook-tester",
    category: "TEST & DEBUG",
    size: "medium",
    icon: "Send",
    preview: "POST /webhook → 200 OK",
    volume: 1000,
    cpc: 4.90, trend: "up" as const,
  },
  {
    id: "javascript-obfuscator",
    name: "JavaScript Obfuscator",
    description: "Obfuscate JS: rename vars, minify, encode strings",
    tags: ["javascript", "js", "obfuscate", "minify", "protect", "code"],
    route: "/javascript-obfuscator",
    category: "FORMAT & VALIDATE",
    size: "standard",
    icon: "Shield",
    preview: "function() {} → _0x00a()",
    volume: 1300,
    cpc: 3.67, trend: "up" as const,
  },
  {
    id: "yaml-to-json",
    name: "YAML to JSON",
    description: "Convert YAML to JSON instantly",
    tags: ["yaml", "yml", "json", "convert", "transform"],
    route: "/yaml-to-json",
    category: "CONVERT",
    size: "standard",
    icon: "ArrowRightLeft",
    preview: "key: value → {\"key\":\"value\"}",
    volume: 2400,
    cpc: 5.20, trend: "up" as const,
  },
  {
    id: "schema-markup-generator",
    name: "Schema Markup Generator",
    description: "Generate JSON-LD schema markup for SEO",
    tags: ["schema", "json-ld", "structured data", "seo", "rich results", "google"],
    route: "/schema-markup-generator",
    category: "SEO",
    size: "medium",
    icon: "Search",
    preview: "Article, FAQ, Product → JSON-LD",
    volume: 1300,
    cpc: 5.12, trend: "up" as const,
  },
  {
    id: "xml-to-csv",
    name: "XML to CSV",
    description: "Convert XML to CSV with auto-detected columns",
    tags: ["xml", "csv", "convert", "spreadsheet", "flatten"],
    route: "/xml-to-csv",
    category: "CONVERT",
    size: "standard",
    icon: "FileText",
    preview: "<item>...</item> → CSV",
    volume: 1900,
    cpc: 3.48, trend: "up" as const,
  },
  // ─── New Batch: Tier A ───
  {
    id: "json-diff",
    name: "JSON Diff",
    description: "Compare two JSON objects with color-coded tree diff",
    tags: ["json", "diff", "compare", "difference", "merge"],
    route: "/json-diff",
    category: "COMPARE",
    size: "medium",
    icon: "GitCompare",
    preview: "{a:1} vs {a:2} → changed",
    volume: 6600,
    cpc: 6.09, trend: "up" as const,
  },
  {
    id: "json-to-xml",
    name: "JSON to XML",
    description: "Convert JSON to XML format",
    tags: ["json", "xml", "convert", "transform"],
    route: "/json-to-xml",
    category: "CONVERT",
    size: "standard",
    icon: "Code",
    preview: "{\"key\":\"val\"} → <key>val</key>",
    volume: 1300,
    cpc: 3.01, trend: "flat" as const,
  },
  {
    id: "keyword-density-checker",
    name: "Keyword Density Checker",
    description: "Analyze keyword frequency and density for SEO",
    tags: ["keyword", "density", "seo", "content", "frequency", "analysis"],
    route: "/keyword-density-checker",
    category: "SEO",
    size: "standard",
    icon: "Search",
    preview: "text → top keywords + density %",
    volume: 1300,
    cpc: 3.39, trend: "up" as const,
  },
  {
    id: "readability-checker",
    name: "Readability Checker",
    description: "Flesch-Kincaid, Gunning Fog, SMOG, ARI scores",
    tags: ["readability", "flesch", "kincaid", "fog", "grade", "score", "seo"],
    route: "/readability-checker",
    category: "SEO",
    size: "medium",
    icon: "FileText",
    preview: "text → Grade 8 · Easy to read",
    volume: 2900,
    cpc: 2.69, trend: "up" as const,
  },
  {
    id: "markdown-to-pdf",
    name: "Markdown to PDF",
    description: "Convert Markdown to PDF and download",
    tags: ["markdown", "md", "pdf", "convert", "export", "document"],
    route: "/markdown-to-pdf",
    category: "PDF",
    size: "medium",
    icon: "FileText",
    preview: "# Heading → PDF download",
    volume: 6600,
    cpc: 3.09, trend: "up" as const,
  },
  {
    id: "html-minifier",
    name: "HTML Minifier",
    description: "Minify HTML: remove comments, whitespace, optional tags",
    tags: ["html", "minify", "compress", "whitespace", "comments", "optimize"],
    route: "/html-minifier",
    category: "FORMAT & VALIDATE",
    size: "standard",
    icon: "Code",
    preview: "<div>  </div> → <div></div>",
    volume: 1300,
    cpc: 7.39, trend: "up" as const,
  },
  {
    id: "subnet-calculator",
    name: "Subnet Calculator",
    description: "Calculate CIDR subnet: network, hosts, broadcast",
    tags: ["subnet", "cidr", "ip", "network", "mask", "broadcast"],
    route: "/subnet-calculator",
    category: "NETWORK",
    size: "standard",
    icon: "Network",
    preview: "10.0.0.0/16 → 65,534 hosts",
    volume: 49500,
    cpc: 5.36, trend: "up" as const,
  },
  {
    id: "regex-cheat-sheet",
    name: "Regex Cheat Sheet",
    description: "Searchable regex reference: syntax, examples, patterns",
    tags: ["regex", "regular expression", "cheat sheet", "reference", "patterns"],
    route: "/regex-cheat-sheet",
    category: "FORMAT & VALIDATE",
    size: "medium",
    icon: "FileText",
    preview: "\\d+ · (?=...) · [a-z]{2,}",
    volume: 5400,
    cpc: 0.70, trend: "up" as const,
  },
  {
    id: "text-compare",
    name: "Text Compare",
    description: "Compare two texts with line-by-line diff view",
    tags: ["text", "compare", "diff", "difference", "line"],
    route: "/text-compare",
    category: "COMPARE",
    size: "standard",
    icon: "GitCompare",
    preview: "+ added line\n- removed line",
    volume: 4400,
    cpc: 0.01, trend: "up" as const,
  },
  {
    id: "cron-generator",
    name: "Cron Expression Generator",
    description: "Build and explain cron job schedules visually",
    tags: ["cron", "crontab", "schedule", "job", "timer"],
    route: "/cron",
    category: "GENERATE" as const,
    size: "standard" as const,
    icon: "Clock",
    preview: "*/5 * * * * → every 5 min",
    volume: 5400,
    cpc: 0, trend: "up" as const,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions with live highlighting",
    tags: ["regex", "regular expression", "test", "match", "pattern"],
    route: "/regex",
    category: "TEST & DEBUG" as const,
    size: "standard" as const,
    icon: "Search",
    preview: "/\\w+/g → match words",
    volume: 1000,
    cpc: 0, trend: "flat" as const,
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and reading time",
    tags: ["word", "count", "character", "sentence", "reading time"],
    route: "/words",
    category: "GENERATE" as const,
    size: "standard" as const,
    icon: "Type",
    preview: "128 words · 4 min read",
    volume: 1000,
    cpc: 0, trend: "flat" as const,
  },
  // ─── Tier S New Tools ───
  {
    id: "discord-timestamp",
    name: "Discord Timestamp Generator",
    description: "Generate Discord timestamp tags for any date/time",
    tags: ["discord", "timestamp", "epoch", "format", "time"],
    route: "/discord-timestamp-generator",
    category: "GENERATE",
    size: "medium",
    icon: "Clock",
    preview: "<t:1234567890:R> → 2 months ago",
    volume: 9900,
    cpc: 0.5, trend: "up" as const,
  },
  {
    id: "saml-decoder",
    name: "SAML Decoder",
    description: "Decode base64 SAML responses and assertions",
    tags: ["saml", "sso", "base64", "decode", "xml", "assertion", "shibboleth"],
    route: "/saml-decoder",
    category: "ENCODE & DECODE",
    size: "medium",
    icon: "KeyRound",
    preview: "base64 → XML · NameID · Issuer",
    volume: 1600,
    cpc: 5.31, trend: "up" as const,
  },
  {
    id: "certificate-decoder",
    name: "Certificate Decoder",
    description: "Decode PEM certificates and CSRs (Subject, SANs, validity)",
    tags: ["certificate", "x509", "pem", "csr", "ssl", "tls", "decode", "openssl", "san"],
    route: "/certificate-decoder",
    category: "ENCODE & DECODE",
    size: "medium",
    icon: "Shield",
    preview: "PEM → Subject · SANs · Validity",
    volume: 5300,
    cpc: 6.43, trend: "up" as const,
  },
  {
    id: "hex-calculator",
    name: "Hex Calculator",
    description: "Hex arithmetic: add, subtract, AND, OR, XOR, shifts",
    tags: ["hex", "hexadecimal", "calculator", "bitwise", "and", "or", "xor", "not", "arithmetic"],
    route: "/hex-calculator",
    category: "CONVERT",
    size: "medium",
    icon: "Hash",
    preview: "0xFF + 0x01 = 0x100",
    volume: 8100,
    cpc: 0.5, trend: "up" as const,
  },
  {
    id: "guid-generator",
    name: "GUID Generator",
    description: "Generate GUIDs (UUID v4) — Microsoft/Windows ecosystem",
    tags: ["guid", "uuid", "generate", "random", "microsoft", "dotnet", "csharp", ".net"],
    route: "/guid-generator",
    category: "GENERATE",
    size: "standard",
    icon: "Fingerprint",
    preview: "{XXXXXXXX-XXXX-4XXX-YXXX-XXXXXXXXXXXX}",
    volume: 9900,
    cpc: 0.1, trend: "up" as const,
  },
  {
    id: "markdown-editor",
    name: "Markdown Editor",
    description: "Live Markdown editor with split-pane preview and toolbar",
    tags: ["markdown", "editor", "preview", "live", "write", "md"],
    route: "/markdown-editor",
    category: "FORMAT & VALIDATE",
    size: "featured",
    icon: "FileText",
    preview: "# Heading\n**bold** *italic*",
    volume: 1900,
    cpc: 0.5, trend: "up" as const,
  },
];

export const toolsByCategory = tools.reduce(
  (acc, tool) => {
    if (!acc[tool.category]) acc[tool.category] = [];
    acc[tool.category].push(tool);
    return acc;
  },
  {} as Record<ToolCategory, Tool[]>
);

export const categories: ToolCategory[] = [
  "FORMAT & VALIDATE",
  "ENCODE & DECODE",
  "CONVERT",
  "GENERATE",
  "PDF",
  "SEO",
  "NETWORK",
  "COMPARE",
  "TEST & DEBUG",
];
