"use client";

import { useWebMCP } from "@/lib/use-webmcp";

import { useState } from "react";
import { ToolLayout } from "@/components/tool-layout";
import { SplitPane } from "@/components/split-pane";
import { CopyButton } from "@/components/copy-button";
import { Trash2 } from "lucide-react";

const SAMPLE_CSV = `id,name,email,age,active
1,Alice Johnson,alice@example.com,30,true
2,Bob Smith,bob@example.com,25,false
3,Carol White,carol@example.com,35,true`;

function inferType(values: string[]): string {
  const nonEmpty = values.filter((v) => v !== "");
  if (nonEmpty.length === 0) return "TEXT";
  if (nonEmpty.every((v) => /^-?\d+$/.test(v))) return "INTEGER";
  if (nonEmpty.every((v) => /^-?\d+(\.\d+)?$/.test(v))) return "DECIMAL(10,2)";
  if (nonEmpty.every((v) => /^(true|false|0|1)$/i.test(v))) return "BOOLEAN";
  if (nonEmpty.every((v) => /^\d{4}-\d{2}-\d{2}/.test(v))) return "DATE";
  const maxLen = Math.max(...nonEmpty.map((v) => v.length));
  if (maxLen <= 255) return "VARCHAR(255)";
  return "TEXT";
}

function parseCsv(raw: string): { headers: string[]; rows: string[][] } {
  const lines = raw.trim().split("\n").filter(Boolean);
  if (lines.length === 0) return { headers: [], rows: [] };

  function parseLine(line: string): string[] {
    const result: string[] = [];
    let cur = "";
    let inQuote = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (ch === '"') {
        if (inQuote && line[i + 1] === '"') {
          cur += '"';
          i++;
        } else {
          inQuote = !inQuote;
        }
      } else if (ch === "," && !inQuote) {
        result.push(cur.trim());
        cur = "";
      } else {
        cur += ch;
      }
    }
    result.push(cur.trim());
    return result;
  }

  const headers = parseLine(lines[0]);
  const rows = lines.slice(1).map(parseLine);
  return { headers, rows };
}

function csvToSql(csv: string, tableName: string): string {
  const { headers, rows } = parseCsv(csv);
  if (headers.length === 0) return "";

  // Infer column types from data
  const colTypes = headers.map((_, i) => inferType(rows.map((r) => r[i] ?? "")));

  const escapeId = (s: string) => `\`${s.replace(/`/g, "``")}\``;
  const escapeVal = (v: string) => {
    if (v === "" || v.toLowerCase() === "null") return "NULL";
    if (/^-?\d+(\.\d+)?$/.test(v)) return v;
    if (/^(true|false)$/i.test(v)) return v.toLowerCase() === "true" ? "TRUE" : "FALSE";
    return `'${v.replace(/'/g, "''")}'`;
  };

  const cols = headers
    .map((h, i) => `  ${escapeId(h)} ${colTypes[i]}`)
    .join(",\n");

  const createTable = `CREATE TABLE ${escapeId(tableName)} (\n${cols}\n);`;

  const insertRows = rows
    .filter((r) => r.some((v) => v !== ""))
    .map((row) => {
      const vals = headers.map((_, i) => escapeVal(row[i] ?? ""));
      return `INSERT INTO ${escapeId(tableName)} (${headers.map(escapeId).join(", ")}) VALUES (${vals.join(", ")});`;
    })
    .join("\n");

  return `-- Generated by devpick.sh/csv-to-sql\n\n${createTable}\n\n${insertRows}`;
}

export function CsvToSqlTool() {
  useWebMCP({
    name: "csvToSQL",
    description: "Convert CSV data to SQL CREATE TABLE and INSERT statements",
    inputSchema: {
      type: "object" as const,
      properties: {
      "csv": {
            "type": "string",
            "description": "CSV data"
      },
      "tableName": {
            "type": "string",
            "description": "SQL table name (default: data)"
      }
},
      required: ["csv"],
    },
    execute: async (params) => {
      return { content: [{ type: "text", text: "Use the web UI for CSV to SQL conversion" }] };
    },
  });

  const [input, setInput] = useState(SAMPLE_CSV);
  const [tableName, setTableName] = useState("my_table");
  const [error, setError] = useState("");

  let output = "";
  if (input.trim()) {
    try {
      output = csvToSql(input, tableName || "my_table");
      if (error) setError("");
    } catch (e) {
      output = "";
      if ((e as Error).message !== error) setTimeout(() => setError((e as Error).message), 0);
    }
  }

  return (
    <ToolLayout
      agentReady
      title="CSV to SQL Converter"
      description="Paste CSV data and instantly get CREATE TABLE + INSERT statements. Runs entirely in your browser."
    >
      {/* Options bar */}
      <div className="flex flex-wrap items-center gap-3 mb-4">
        <label className="flex items-center gap-2 text-sm text-text-secondary">
          Table name:
          <input
            value={tableName}
            onChange={(e) => setTableName(e.target.value)}
            className="px-2 py-1 text-sm font-mono border border-border-subtle rounded bg-surface-raised text-text-primary focus:outline-none focus:ring-1 focus:ring-accent w-36"
            placeholder="my_table"
          />
        </label>
        <div className="ml-auto flex gap-2">
          <button
            onClick={() => {
              setInput("");
              setError("");
            }}
            className="action-btn"
          >
            <Trash2 size={13} />
            Clear
          </button>
          <CopyButton text={output} />
        </div>
      </div>

      <SplitPane
        left={
          <div className="flex flex-col h-full">
            <div className="pane-label">CSV Input</div>
            <textarea
              value={input}
              onChange={(e) => {
                setInput(e.target.value);
                setError("");
              }}
              placeholder="Paste CSV here (first row = column headers)"
              className="tool-textarea flex-1"
              spellCheck={false}
            />
          </div>
        }
        right={
          <div className="flex flex-col h-full">
            <div className="pane-label">SQL Output</div>
            <div className="output-panel flex-1">
              {error ? (
                <span className="text-[var(--dp-error)] text-xs font-mono">{error}</span>
              ) : output ? (
                <pre className="text-[13px] font-mono leading-relaxed whitespace-pre-wrap break-all text-text-primary animate-fade-in">
                  {output}
                </pre>
              ) : (
                <span className="text-text-ghost font-mono text-[13px]">
                  SQL will appear here…
                </span>
              )}
            </div>
          </div>
        }
      />

      {/* Related Tools */}
      <div className="mt-8 pt-6 border-t border-border-subtle">
        <h2 className="text-sm font-semibold text-text-secondary mb-3">Related Tools</h2>
        <div className="flex flex-wrap gap-2">
          {[
            { name: "CSV to JSON", href: "/csv-to-json" },
            { name: "CSV Viewer", href: "/csv-viewer" },
            { name: "SQL Formatter", href: "/sql-formatter" },
            { name: "JSON Formatter", href: "/json-formatter" },
          ].map((t) => (
            <a
              key={t.href}
              href={t.href}
              className="text-xs text-accent hover:underline px-2 py-1 rounded bg-[var(--dp-bg-subtle)]"
            >
              {t.name}
            </a>
          ))}
        </div>
      </div>
    </ToolLayout>
  );
}
